#!/bin/bash

deepspeed llava/train/train_mem_finetune_lora.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 1e-5 \
    --deepspeed ./scripts/zero2.json \
    --model_base liuhaotian/llava-v1.5-7b\
    --model_name_or_path ../diffusion_policy_for_action/llava_checkpoints/llava-v1.5-7b_lora_mpm \
    --version v1 \
    --data_path ../diffusion_policy_for_action/train_datasets/continue_leanring_data/ThreePieceAssembly_D0_10_continue_learning.json \
    --image_folder ../diffusion_policy_for_action/train_datasets/continue_leanring_data \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ../diffusion_policy_for_action/llava_checkpoints/llava-v1.5-7b_lora_mpm_ThreePieceAssembly_D0_lifelong_learning\
    --num_train_epochs 5 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
