_target_: trajectory_data.TrajectoryIndexSpeedDataset
kwargs:
  data_dir: "${root_path}/train_datasets/${language_condition}"
  data_path: ${data_path}
  language_condition: ${language_condition}
  batch_size: ${batch_size}
  frame_length: ${frame_length}
  have_depth: ${have_depth}
  have_ego: ${have_ego}
  demonstration_num: ${demonstration_num}
  augmentation_cfg: []