defaults:
  - policy: transformer_policy
  - dataset: load_chunking
  - optimizer: adam
  - eval_dataset: eval_chunking


lr: 0.0001
seed: 42
frame_length: 5
action_chunking: true
action_length: 12
action_weight_init: 0
use_temporal_ensemble: false
batch_size: 384
num_workers: 8
language_condition: rt_h
data_path: dataset_mapping.json

language_codebook_size: 21

loss_threshold: 0.01
task_name: coffee_task_language
extra_dim: 9
demonstration_num: 500

action_shape: 7
image_shape: [224,224]
device: cuda
# root_path: "/ailab/user/xiawenke/workspace/generalizable_manipulation/release_code/diffusion_policy_for_action"
root_path: ${oc.env:CURRENT_DIR}
exp_name: motion_conditioned_diffusion_policy
epoch: 201
save_interval: 100
have_depth: false
have_ego: true


use_language_idx: true
kernel_size: 5
num_diffusion_iters: 5
use_flatten: false
visual_hidden_dim: 512
hidden_dim: 512
diffusion_hidden_dim: 512


notes: "None"
split_ratio: 0.9
eval_interval: 5

load_bc: false
weight_name: motion
bc_name: motion_create
bc_path: ${root_path}/weights/${bc_name}/${weight_name}.pth


hydra:
  run:
    dir: ./ckpt/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${task_name}
  sweep:
    dir: test/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
