defaults:
  - policy: motion_policy
  - dataset: motion_dataset
  - optimizer: adam

seed: 42

num_workers: 8
batch_size: 1024
epoch: 201
image_dir: /dev/shm/coffee
json_path: /ailab/user/xiawenke/workspace/generalizable_manipulation/mimicgen_environments/feedback/train_datasets/new_llava_data/distribution_reduced_coffee_llava.json
numpy_path: /dev/shm/coffee/distributed_coffee_llava.npy


lr: 0.0003
device: cuda
language_codebook_size: 20
exp_name: motion_prediction
task_name: motion_prediction

split_ratio: 0.9
eval_interval: 5

load_bc: false
weight_name: motion


hydra:
  run:
    dir: ./train_iclr_ckpts/${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${task_name}
  sweep:
    dir: test/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
