_target_: policies.diffusion_policy.ConditionalUnet1D
network_kwargs:
  input_dim: ${policy.action_shape}
  horizon: ${policy.action_length}
  global_cond_dim: ${diffusion_hidden_dim}
  num_diffusion_iters: ${num_diffusion_iters}
  kernel_size: ${kernel_size}

