_target_: policies.policy_head.QueryDecoderGMMHead
network_kwargs:
  input_size: ${policy.hidden_dim}
  output_size: ${policy.action_shape}
  action_length: ${action_length}
  num_layers: 1
  num_heads: 4
  